Student.create(:email =>"a.merzi@yahoo.com", :password =>"helloworld", :f_name => "Anees", :image =>"userimage.png", :school_id =>"1", :music =>"5", :saturday =>"5", :hobby =>"5", :sleep =>"5", :major =>"5", :gender =>"1")
Student.create(:email =>"b.merzi@yahoo.com", :password =>"helloworld", :f_name => "Manny", :image =>"userimage.png", :school_id =>"1", :music =>"2", :saturday =>"2", :hobby =>"2", :sleep =>"2", :major =>"2", :gender =>"1")
Student.create(:email =>"c.merzi@yahoo.com", :password =>"helloworld", :f_name => "Alberto", :image =>"userimage.png", :school_id =>"1", :music =>"3", :saturday =>"3", :hobby =>"3", :sleep =>"5", :major =>"5", :gender =>"1")
Student.create(:email =>"d.merzi@yahoo.com", :password =>"helloworld", :f_name => "Luis", :image =>"userimage.png", :school_id =>"1", :music =>"0", :saturday =>"0", :hobby =>"0", :sleep =>"0", :major =>"10", :gender =>"1")
Student.create(:email =>"e.merzi@yahoo.com", :password =>"helloworld", :f_name => "Mary", :image =>"userimage.png", :school_id =>"1", :music =>"1", :saturday =>"1", :hobby =>"5", :sleep =>"3", :major =>"2", :gender =>"1")
Student.create(:email =>"f.merzi@yahoo.com", :password =>"helloworld", :f_name => "Hwason", :image =>"userimage.png", :school_id =>"1", :music =>"5", :saturday =>"1", :hobby =>"5", :sleep =>"4", :major =>"2", :gender =>"1")
Student.create(:email =>"g.merzi@yahoo.com", :password =>"helloworld", :f_name => "Anitha", :image =>"userimage.png", :school_id =>"1", :music =>"2", :saturday =>"1", :hobby =>"3", :sleep =>"3", :major =>"2", :gender =>"1")
Student.create(:email =>"h.merzi@yahoo.com", :password =>"helloworld", :f_name => "Joe", :image =>"userimage.png", :school_id =>"1", :music =>"3", :saturday =>"2", :hobby =>"1", :sleep =>"2", :major =>"2", :gender =>"1")
Student.create(:email =>"i.merzi@yahoo.com", :password =>"helloworld", :f_name => "Ronda", :image =>"userimage.png", :school_id =>"1", :music =>"2", :saturday =>"4", :hobby =>"1", :sleep =>"2", :major =>"2", :gender =>"1")
Student.create(:email =>"j.merzi@yahoo.com", :password =>"helloworld", :f_name => "Dania", :image =>"userimage.png", :school_id =>"1", :music =>"1", :saturday =>"4", :hobby =>"1", :sleep =>"2", :major =>"2", :gender =>"1")
Student.create(:email =>"k.merzi@yahoo.com", :password =>"helloworld", :f_name => "Roger", :image =>"userimage.png", :school_id =>"1", :music =>"5", :saturday =>"4", :hobby =>"1", :sleep =>"3", :major =>"2", :gender =>"1")
Student.create(:email =>"l.merzi@yahoo.com", :password =>"helloworld", :f_name => "Mike", :image =>"userimage.png", :school_id =>"1", :music =>"5", :saturday =>"4", :hobby =>"2", :sleep =>"3", :major =>"2", :gender =>"1")
Student.create(:email =>"m.merzi@yahoo.com", :password =>"helloworld", :f_name => "Caroline", :image =>"userimage.png", :school_id =>"1", :music =>"5", :saturday =>"4", :hobby =>"5", :sleep =>"1", :major =>"1", :gender =>"2")
Student.create(:email =>"n.merzi@yahoo.com", :password =>"helloworld", :f_name => "Dominick", :image =>"userimage.png", :school_id =>"1", :music =>"3", :saturday =>"4", :hobby =>"3", :sleep =>"2", :major =>"1", :gender =>"2")
Student.create(:email =>"o.merzi@yahoo.com", :password =>"helloworld", :f_name => "Samantha", :image =>"userimage.png", :school_id =>"1", :music =>"1", :saturday =>"4", :hobby =>"4", :sleep =>"3", :major =>"1", :gender =>"2")

# #change email, name
# Student.create(:email =>"a.merzi@yahoo.com", :password =>"helloworld", :f_name => "Anees", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"b.merzi@yahoo.com", :password =>"helloworld", :f_name => "Manny", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"c.merzi@yahoo.com", :password =>"helloworld", :f_name => "Alberto", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"d.merzi@yahoo.com", :password =>"helloworld", :f_name => "Luis", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"e.merzi@yahoo.com", :password =>"helloworld", :f_name => "Mary", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"f.merzi@yahoo.com", :password =>"helloworld", :f_name => "Hwason", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"g.merzi@yahoo.com", :password =>"helloworld", :f_name => "Anitha", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"h.merzi@yahoo.com", :password =>"helloworld", :f_name => "Joe", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"i.merzi@yahoo.com", :password =>"helloworld", :f_name => "Ronda", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"j.merzi@yahoo.com", :password =>"helloworld", :f_name => "Dania", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"k.merzi@yahoo.com", :password =>"helloworld", :f_name => "Roger", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"l.merzi@yahoo.com", :password =>"helloworld", :f_name => "Mike", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"m.merzi@yahoo.com", :password =>"helloworld", :f_name => "Caroline", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"n.merzi@yahoo.com", :password =>"helloworld", :f_name => "Dominick", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"o.merzi@yahoo.com", :password =>"helloworld", :f_name => "Samantha", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"a.merzi@yahoo.com", :password =>"helloworld", :f_name => "Anees", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"b.merzi@yahoo.com", :password =>"helloworld", :f_name => "Manny", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"c.merzi@yahoo.com", :password =>"helloworld", :f_name => "Alberto", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"d.merzi@yahoo.com", :password =>"helloworld", :f_name => "Luis", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"e.merzi@yahoo.com", :password =>"helloworld", :f_name => "Mary", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"f.merzi@yahoo.com", :password =>"helloworld", :f_name => "Hwason", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"g.merzi@yahoo.com", :password =>"helloworld", :f_name => "Anitha", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"h.merzi@yahoo.com", :password =>"helloworld", :f_name => "Joe", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"i.merzi@yahoo.com", :password =>"helloworld", :f_name => "Ronda", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"j.merzi@yahoo.com", :password =>"helloworld", :f_name => "Dania", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"k.merzi@yahoo.com", :password =>"helloworld", :f_name => "Roger", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"l.merzi@yahoo.com", :password =>"helloworld", :f_name => "Mike", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"m.merzi@yahoo.com", :password =>"helloworld", :f_name => "Caroline", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"n.merzi@yahoo.com", :password =>"helloworld", :f_name => "Dominick", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"o.merzi@yahoo.com", :password =>"helloworld", :f_name => "Samantha", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"a.merzi@yahoo.com", :password =>"helloworld", :f_name => "Anees", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"b.merzi@yahoo.com", :password =>"helloworld", :f_name => "Manny", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"c.merzi@yahoo.com", :password =>"helloworld", :f_name => "Alberto", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"d.merzi@yahoo.com", :password =>"helloworld", :f_name => "Luis", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"e.merzi@yahoo.com", :password =>"helloworld", :f_name => "Mary", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"f.merzi@yahoo.com", :password =>"helloworld", :f_name => "Hwason", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"g.merzi@yahoo.com", :password =>"helloworld", :f_name => "Anitha", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"h.merzi@yahoo.com", :password =>"helloworld", :f_name => "Joe", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"i.merzi@yahoo.com", :password =>"helloworld", :f_name => "Ronda", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"j.merzi@yahoo.com", :password =>"helloworld", :f_name => "Dania", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"k.merzi@yahoo.com", :password =>"helloworld", :f_name => "Roger", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"l.merzi@yahoo.com", :password =>"helloworld", :f_name => "Mike", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"m.merzi@yahoo.com", :password =>"helloworld", :f_name => "Caroline", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"n.merzi@yahoo.com", :password =>"helloworld", :f_name => "Dominick", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"o.merzi@yahoo.com", :password =>"helloworld", :f_name => "Samantha", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"a.merzi@yahoo.com", :password =>"helloworld", :f_name => "Anees", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"b.merzi@yahoo.com", :password =>"helloworld", :f_name => "Manny", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"c.merzi@yahoo.com", :password =>"helloworld", :f_name => "Alberto", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"d.merzi@yahoo.com", :password =>"helloworld", :f_name => "Luis", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"e.merzi@yahoo.com", :password =>"helloworld", :f_name => "Mary", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"f.merzi@yahoo.com", :password =>"helloworld", :f_name => "Hwason", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"g.merzi@yahoo.com", :password =>"helloworld", :f_name => "Anitha", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"h.merzi@yahoo.com", :password =>"helloworld", :f_name => "Joe", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"i.merzi@yahoo.com", :password =>"helloworld", :f_name => "Ronda", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"j.merzi@yahoo.com", :password =>"helloworld", :f_name => "Dania", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"k.merzi@yahoo.com", :password =>"helloworld", :f_name => "Roger", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"l.merzi@yahoo.com", :password =>"helloworld", :f_name => "Mike", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"m.merzi@yahoo.com", :password =>"helloworld", :f_name => "Caroline", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"n.merzi@yahoo.com", :password =>"helloworld", :f_name => "Dominick", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"o.merzi@yahoo.com", :password =>"helloworld", :f_name => "Samantha", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"a.merzi@yahoo.com", :password =>"helloworld", :f_name => "Anees", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"b.merzi@yahoo.com", :password =>"helloworld", :f_name => "Manny", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"c.merzi@yahoo.com", :password =>"helloworld", :f_name => "Alberto", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"d.merzi@yahoo.com", :password =>"helloworld", :f_name => "Luis", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"e.merzi@yahoo.com", :password =>"helloworld", :f_name => "Mary", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"f.merzi@yahoo.com", :password =>"helloworld", :f_name => "Hwason", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"g.merzi@yahoo.com", :password =>"helloworld", :f_name => "Anitha", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"h.merzi@yahoo.com", :password =>"helloworld", :f_name => "Joe", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"i.merzi@yahoo.com", :password =>"helloworld", :f_name => "Ronda", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"j.merzi@yahoo.com", :password =>"helloworld", :f_name => "Dania", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"k.merzi@yahoo.com", :password =>"helloworld", :f_name => "Roger", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"l.merzi@yahoo.com", :password =>"helloworld", :f_name => "Mike", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"m.merzi@yahoo.com", :password =>"helloworld", :f_name => "Caroline", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"n.merzi@yahoo.com", :password =>"helloworld", :f_name => "Dominick", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")
# Student.create(:email =>"o.merzi@yahoo.com", :password =>"helloworld", :f_name => "Samantha", :image =>"userimage.png", :school_id =>"1", :music =>"", :saturday =>"", :hobby =>"", :sleep =>"", :major =>"", :gender =>"")


School.create(:name =>"TAMUCT")

Dorm.create(:name =>"Warrior Dorm", :price =>"3000", :location =>"Near the Library", :num_roomates =>"2", :dorm_image =>"dorm.png", :room_image =>"room.png", :school_id =>"1")

Room.create(:room_num =>"1A", :dorm_id =>"1")
Room.create(:room_num =>"2A", :dorm_id =>"1")
Room.create(:room_num =>"3A", :dorm_id =>"1")
Room.create(:room_num =>"4A", :dorm_id =>"1")
Room.create(:room_num =>"5A", :dorm_id =>"1")
Room.create(:room_num =>"6A", :dorm_id =>"1")
Room.create(:room_num =>"7A", :dorm_id =>"1")
Room.create(:room_num =>"8A", :dorm_id =>"1")
Room.create(:room_num =>"9A", :dorm_id =>"1")
Room.create(:room_num =>"10A", :dorm_id =>"1")
Room.create(:room_num =>"11A", :dorm_id =>"1")
Room.create(:room_num =>"12A", :dorm_id =>"1")
Room.create(:room_num =>"13A", :dorm_id =>"1")
Room.create(:room_num =>"14A", :dorm_id =>"1")
Room.create(:room_num =>"15A", :dorm_id =>"1")
Room.create(:room_num =>"16A", :dorm_id =>"1")
Room.create(:room_num =>"17A", :dorm_id =>"1")
Room.create(:room_num =>"18A", :dorm_id =>"1")
Room.create(:room_num =>"19A", :dorm_id =>"1")
Room.create(:room_num =>"20A", :dorm_id =>"1")
Room.create(:room_num =>"1B", :dorm_id =>"1")
Room.create(:room_num =>"2B", :dorm_id =>"1")
Room.create(:room_num =>"3B", :dorm_id =>"1")
Room.create(:room_num =>"4B", :dorm_id =>"1")
Room.create(:room_num =>"5B", :dorm_id =>"1")
Room.create(:room_num =>"6B", :dorm_id =>"1")
Room.create(:room_num =>"7B", :dorm_id =>"1")
Room.create(:room_num =>"8B", :dorm_id =>"1")
Room.create(:room_num =>"9B", :dorm_id =>"1")
Room.create(:room_num =>"10B", :dorm_id =>"1")
Room.create(:room_num =>"11B", :dorm_id =>"1")
Room.create(:room_num =>"12B", :dorm_id =>"1")
Room.create(:room_num =>"13B", :dorm_id =>"1")
Room.create(:room_num =>"14B", :dorm_id =>"1")
Room.create(:room_num =>"15B", :dorm_id =>"1")
Room.create(:room_num =>"16B", :dorm_id =>"1")
Room.create(:room_num =>"17B", :dorm_id =>"1")
Room.create(:room_num =>"18B", :dorm_id =>"1")
Room.create(:room_num =>"19B", :dorm_id =>"1")
Room.create(:room_num =>"20B", :dorm_id =>"1")
