Student.create(:email =>"a.merzi@yahoo.com", :password =>"helloworld", :f_name => "Anees", :image =>"userimage.png", :school_id =>"1", :music =>"5", :saturday =>"5", :hobby =>"5", :sleep =>"5", :major =>"5", :gender =>"1", :score =>"25") 
Student.create(:email =>"b.merzi@yahoo.com", :password =>"helloworld", :f_name => "Manny", :image =>"userimage.png", :school_id =>"1", :music =>"2", :saturday =>"12", :hobby =>"2", :sleep =>"2", :major =>"2", :gender =>"1", :score =>"20")
Student.create(:email =>"c.merzi@yahoo.com", :password =>"helloworld", :f_name => "Alberto", :image =>"userimage.png", :school_id =>"11", :music =>"3", :saturday =>"3", :hobby =>"3", :sleep =>"5", :major =>"5", :gender =>"1", :score =>"19")
Student.create(:email =>"d.merzi@yahoo.com", :password =>"helloworld", :f_name => "Luis", :image =>"userimage.png", :school_id =>"1", :music =>"0", :saturday =>"0", :hobby =>"0", :sleep =>"0", :major =>"10", :gender =>"1", :score =>"10")
Student.create(:email =>"e.merzi@yahoo.com", :password =>"helloworld", :f_name => "Mary", :image =>"userimage.png", :school_id =>"1", :music =>"1", :saturday =>"1", :hobby =>"5", :sleep =>"3", :major =>"2", :gender =>"2", :score =>"12")
Student.create(:email =>"f.merzi@yahoo.com", :password =>"helloworld", :f_name => "Jason", :image =>"userimage.png", :school_id =>"1", :music =>"5", :saturday =>"1", :hobby =>"5", :sleep =>"4", :major =>"2", :gender =>"1", :score =>"17")
Student.create(:email =>"g.merzi@yahoo.com", :password =>"helloworld", :f_name => "Anitha", :image =>"userimage.png", :school_id =>"10", :music =>"2", :saturday =>"1", :hobby =>"3", :sleep =>"3", :major =>"2", :gender =>"2", :score =>"11")
Student.create(:email =>"h.merzi@yahoo.com", :password =>"helloworld", :f_name => "Joe", :image =>"userimage.png", :school_id =>"1", :music =>"3", :saturday =>"2", :hobby =>"11", :sleep =>"2", :major =>"2", :gender =>"1", :score =>"20")
Student.create(:email =>"i.merzi@yahoo.com", :password =>"helloworld", :f_name => "Ronda", :image =>"userimage.png", :school_id =>"1", :music =>"2", :saturday =>"4", :hobby =>"1", :sleep =>"2", :major =>"2", :gender =>"1", :score =>"13")
Student.create(:email =>"j.merzi@yahoo.com", :password =>"helloworld", :f_name => "Dania", :image =>"userimage.png", :school_id =>"1", :music =>"1", :saturday =>"14", :hobby =>"1", :sleep =>"2", :major =>"2", :gender =>"1", :score =>"20")
Student.create(:email =>"k.merzi@yahoo.com", :password =>"helloworld", :f_name => "Roger", :image =>"userimage.png", :school_id =>"1", :music =>"5", :saturday =>"4", :hobby =>"1", :sleep =>"3", :major =>"2", :gender =>"1", :score =>"15")
Student.create(:email =>"l.merzi@yahoo.com", :password =>"helloworld", :f_name => "Mike", :image =>"userimage.png", :school_id =>"1", :music =>"5", :saturday =>"4", :hobby =>"12", :sleep =>"3", :major =>"2", :gender =>"1", :score =>"26")
Student.create(:email =>"m.merzi@yahoo.com", :password =>"helloworld", :f_name => "Caroline", :image =>"userimage.png", :school_id =>"1", :music =>"5", :saturday =>"4", :hobby =>"5", :sleep =>"11", :major =>"1", :gender =>"2", :score =>"26")
Student.create(:email =>"n.merzi@yahoo.com", :password =>"helloworld", :f_name => "Dominique", :image =>"userimage.png", :school_id =>"1", :music =>"3", :saturday =>"4", :hobby =>"3", :sleep =>"8", :major =>"1", :gender =>"2", :score =>"19")
Student.create(:email =>"o.merzi@yahoo.com", :password =>"helloworld", :f_name => "Samantha", :image =>"userimage.png", :school_id =>"1", :music =>"1", :saturday =>"4", :hobby =>"14", :sleep =>"3", :major =>"1", :gender =>"2", :score =>"23")
Student.create(:email =>"p.merzi@yahoo.com", :password =>"helloworld", :f_name => "Anees", :image =>"userimage.png", :school_id =>"1", :music =>"5", :saturday =>"5", :hobby =>"5", :sleep =>"5", :major =>"5", :gender =>"1", :score =>"25")
Student.create(:email =>"q.merzi@yahoo.com", :password =>"helloworld", :f_name => "Manny", :image =>"userimage.png", :school_id =>"1", :music =>"2", :saturday =>"2", :hobby =>"2", :sleep =>"2", :major =>"2", :gender =>"1", :score =>"10")
Student.create(:email =>"r.merzi@yahoo.com", :password =>"helloworld", :f_name => "Alberto", :image =>"userimage.png", :school_id =>"1", :music =>"3", :saturday =>"3", :hobby =>"3", :sleep =>"5", :major =>"5", :gender =>"1", :score =>"14")
Student.create(:email =>"s.merzi@yahoo.com", :password =>"helloworld", :f_name => "Luis", :image =>"userimage.png", :school_id =>"1", :music =>"0", :saturday =>"0", :hobby =>"0", :sleep =>"0", :major =>"10", :gender =>"1", :score =>"10")
Student.create(:email =>"t.merzi@yahoo.com", :password =>"helloworld", :f_name => "Oscar", :image =>"userimage.png", :school_id =>"1", :music =>"1", :saturday =>"1", :hobby =>"15", :sleep =>"3", :major =>"2", :gender =>"10", :score =>"33")
Student.create(:email =>"u.merzi@yahoo.com", :password =>"helloworld", :f_name => "Hwason", :image =>"userimage.png", :school_id =>"1", :music =>"5", :saturday =>"4", :hobby =>"5", :sleep =>"14", :major =>"2", :gender =>"2", :score =>"40")
Student.create(:email =>"v.merzi@yahoo.com", :password =>"helloworld", :f_name => "Anitha", :image =>"userimage.png", :school_id =>"1", :music =>"2", :saturday =>"11", :hobby =>"3", :sleep =>"3", :major =>"2", :gender =>"2", :score =>"29")
Student.create(:email =>"w.merzi@yahoo.com", :password =>"helloworld", :f_name => "Jessica", :image =>"userimage.png", :school_id =>"1", :music =>"3", :saturday =>"2", :hobby =>"1", :sleep =>"2", :major =>"2", :gender =>"2", :score =>"17")
Student.create(:email =>"x.merzi@yahoo.com", :password =>"helloworld", :f_name => "Rachel", :image =>"userimage.png", :school_id =>"1", :music =>"2", :saturday =>"4", :hobby =>"10", :sleep =>"2", :major =>"2", :gender =>"2", :score =>"22")
Student.create(:email =>"y.merzi@yahoo.com", :password =>"helloworld", :f_name => "Jessica", :image =>"userimage.png", :school_id =>"1", :music =>"1", :saturday =>"4", :hobby =>"1", :sleep =>"12", :major =>"2", :gender =>"2", :score =>"27")
Student.create(:email =>"z.merzi@yahoo.com", :password =>"helloworld", :f_name => "Mario", :image =>"userimage.png", :school_id =>"1", :music =>"3", :saturday =>"10", :hobby =>"3", :sleep =>"3", :major =>"2", :gender =>"1", :score =>"15")

School.create(:name =>"TAMUCT")

Dorm.create(:name =>"Warrior Dorm", :price =>"3000", :location =>"Near the Library", :num_roomates =>"2", :dorm_image =>"dorm.png", :room_image =>"room.png", :school_id =>"1")

Room.create(:room_num =>"1A", :dorm_id =>"1")
Room.create(:room_num =>"2A", :dorm_id =>"1")
Room.create(:room_num =>"3A", :dorm_id =>"1")
Room.create(:room_num =>"4A", :dorm_id =>"1")
Room.create(:room_num =>"5A", :dorm_id =>"1")
Room.create(:room_num =>"6A", :dorm_id =>"1")
Room.create(:room_num =>"7A", :dorm_id =>"1")
Room.create(:room_num =>"8A", :dorm_id =>"1")
Room.create(:room_num =>"9A", :dorm_id =>"1")
Room.create(:room_num =>"10A", :dorm_id =>"1")
Room.create(:room_num =>"11A", :dorm_id =>"1")
Room.create(:room_num =>"12A", :dorm_id =>"1")
Room.create(:room_num =>"13A", :dorm_id =>"1")
Room.create(:room_num =>"14A", :dorm_id =>"1")
Room.create(:room_num =>"15A", :dorm_id =>"1")
Room.create(:room_num =>"16A", :dorm_id =>"1")
Room.create(:room_num =>"17A", :dorm_id =>"1")
Room.create(:room_num =>"18A", :dorm_id =>"1")
Room.create(:room_num =>"19A", :dorm_id =>"1")
Room.create(:room_num =>"20A", :dorm_id =>"1")
Room.create(:room_num =>"1B", :dorm_id =>"1")
Room.create(:room_num =>"2B", :dorm_id =>"1")
Room.create(:room_num =>"3B", :dorm_id =>"1")
Room.create(:room_num =>"4B", :dorm_id =>"1")
Room.create(:room_num =>"5B", :dorm_id =>"1")
Room.create(:room_num =>"6B", :dorm_id =>"1")
Room.create(:room_num =>"7B", :dorm_id =>"1")
Room.create(:room_num =>"8B", :dorm_id =>"1")
Room.create(:room_num =>"9B", :dorm_id =>"1")
Room.create(:room_num =>"10B", :dorm_id =>"1")
Room.create(:room_num =>"11B", :dorm_id =>"1")
Room.create(:room_num =>"12B", :dorm_id =>"1")
Room.create(:room_num =>"13B", :dorm_id =>"1")
Room.create(:room_num =>"14B", :dorm_id =>"1")
Room.create(:room_num =>"15B", :dorm_id =>"1")
Room.create(:room_num =>"16B", :dorm_id =>"1")
Room.create(:room_num =>"17B", :dorm_id =>"1")
Room.create(:room_num =>"18B", :dorm_id =>"1")
Room.create(:room_num =>"19B", :dorm_id =>"1")
Room.create(:room_num =>"20B", :dorm_id =>"1")
